server:
  port: 7701
  error:
    whitelabel:
      enabled: true
    include-stacktrace: never

spring:
  application:
  name: Freeton League Core - the system for manage FreeTon League Game Tournaments
  datasource: #JPA / HIBERNATE
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/league_core
    password: postgres
    username: postgres
  session:
    token-name: X-Auth-Token
  # ===============================
  # Kafka configuration
  # ===============================
  kafka:
    bootstrap-servers: ${kafka_bootstrap_servers:localhost:9092}
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${kafka_username:'admin'} password=${kafka_password:'admin-secret'};
        mechanism: PLAIN
      security:
        protocol: SASL_PLAINTEXT
    consumer:
      auto-offset-reset: earliest
      group-id: example
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      max-poll-records: 5
      fetch-max-wait: 360000
      enable-auto-commit: false
      client-id: example
      properties:
        spring.json.trusted.packages: "*"
        #        fetch.min.bytes: 1000
        fetch.min.bytes: 1
        fetch.max.wait.ms: 200000
    producer:
      client-id: example
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 2
    jaas:
      enabled: true
    listener:
      poll-timeout: 180000
      concurrency: 2
      ack-mode: manual_immediate
      idle-event-interval: 200000


config:
  broxus-client:
    debug: false # change to true for mock Client use
    url: http://49.12.10.52:3383
    token: XXXXXXXXXXXXXXXXXXXXXXXXX

freetonleague:
  service:
    leagueId:
      url: http://localhost:7700/api
      access-token: ifU#AxWveGwSAHevjJFx5S*d8K
    leagueFinance:
      access-token: QPhMMkF4GFEL5Vn6F45PHSaC1496
      balance-update-timeout-in-sec: 300
  team:
    invitation:
      token-duration-in-sec: 432000
  tournament:
    auto-start: true

#LOGGING CONFIG
debug: false
debug-rest: true
stacktrace-rest: true

logging:
  level:
    root: INFO
    org:
      apache:
        kafka: INFO
        http:
          wire: INFO
      springframework: WARN #for detailed debug set DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      freetonleague: DEBUG
  file:
    name: \Users\Khsa\FreetonLeague\logs\League_Core_Tournament.log
# ===============================
#Configuring Feign
# ===============================
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        errorDecoder: com.freetonleague.core.cloudclient.util.FeignErrorDecoder
