server:
  port: 7701
  error:
    whitelabel:
      enabled: true
    include-stacktrace: never

spring:
  application:
  name: Freeton League Core - the system for manage FreeTon League Game Tournaments
  datasource: #JPA / HIBERNATE
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/league_core
    password: postgres
    username: postgres
  session:
    token-name: X-Auth-Token

freetonleague:
  service:
    leagueId:
      url: http://localhost:7700/api

#LOGGING CONFIG
logging:
  level:
    root: INFO
    org:
      apache:
        http:
          wire: INFO
      springframework: WARN #for detailed debug set DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      freetonleague: DEBUG
  file:
    name: \Users\Khsa\FreetonLeague\logs\League_Core_Tournament.log

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        errorDecoder: com.freetonleague.core.cloudclient.util.FeignErrorDecoder
