server:
  port: 7701
  error:
    whitelabel:
      enabled: true
    include-stacktrace: never

spring:
  application:
    name: Freeton League Core - the system for manage FreeTon League Game Tournaments
  # ==== JPA / HIBERNATE ====
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/league_core
    password: postgres
    username: postgres

app:
  common:
    settings-refresh-rate: 10000000000
  user:
    utm-source-register-bonus-map:
      test-source: 0
    import: false
    import-test-data: false
  roulette:
    min-bet-amount: 1
    max-bet-amount: 500
    start-bet-amount: 500
    start-delay-seconds: 600
    min-players-count: 2
    max-players-count: 50
    commission-factor: 0.95

config:
  broxus-client:
    debug: false # change to true for mock Client use
    url: http://49.12.10.52:3383
    token: XXXXXXXXXXXXXXXXXXXXXXXXX
  broxus-native-client:
    url: https://api.broxus.com
    token: e6403d45-9ac4-4c07-b5fd-a4a20c2f9f9e
    mock: true
  kuna-client:
    url: https://kuna.io/api
    mock: false
  u-kassa:
    url: https://kuna.io/api
    token: e6403d45-9ac4-4c07-b5fd-a4a20c2f9f9e
    mock: false
  kafka:
    bootstrap-address: localhost:9092
    notifications:
      start-debug: false
      topic-name: NOTIFICATION

freetonleague:
  service-user-prefix: SERVICE_
  system-user-prefix: SYSTEM_
  session:
    header-token-name: X-Auth-Token
    service-token-name: access_token #if change, than also change variable 'staticServiceTokenName'
  service:
    league-id:
      url: http://localhost:7700/api
      service-token: ifU#AxWveGwSAHevjJFx5S*d8K
    league-storage:
      url: http://localhost:7702/api
      service-token: EqUEcXc3#iZCu5hQS!l33O6I3
    league-finance:
      service-token: QPhMMkF4GFEL5Vn6F45PHSaC1496
      balance-update-timeout-in-sec: 300
      product-billing-account-guid: 4cd64ee5-5f54-3eee-a9bb-f19164ef2ac2
      exchange-order-billing-account-guid: 4cd64ee5-5f54-3eee-a9bb-f19164ef2ac2
      system-bonus-user-login: KdnIgwRY0qzedOZ6R2X6T9GtNDz # name of similar service-user from V025__fin_service_user_and_role.sql
      first-ton-bonus-name: first_ton_2021 # name bonus advertisement company (equals utm_source)
      auto-abort-transaction: true
      min-withdraw-value: 10
    telegram-client:
      url: http://localhost:7701/api/notification/test
      service-token: 6qlW08oPKpItBumDah61hE
  docket:
    first_ton_docket_id: 4 #identifier of docket to automatically pay it's participant first ton to their account
    first_ton_bonus_amount: 1
  team:
    invitation:
      token-duration-in-sec: 432000
  tournament:
    auto-start: true

#LOGGING CONFIG
debug: false
debug-rest: true
stacktrace-rest: true

logging:
  level:
    root: INFO
    org:
      apache:
        kafka: ERROR
        http:
          wire: INFO
      springframework: WARN #for detailed debug set DEBUG
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO
    com:
      freetonleague: DEBUG
  file:
    name: \Users\Khsa\FreetonLeague\logs\League_Core_Tournament.log
# ===============================
#Configuring Feign
# ===============================
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        errorDecoder: com.freetonleague.core.cloudclient.util.FeignErrorDecoder
