server:
  port: 7701
  error:
    whitelabel:
      enabled: true
    include-stacktrace: never

spring:
  application:
    name: Freeton League Core - the system for manage FreeTon League Game Tournaments
  # ==== JPA / HIBERNATE ====
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://lid.realgrace.me:5432/league_core
    password: postgres
    username: postgres

app:
  user:
    utm-source-register-bonus-map:
      test-source: 0

config:
  broxus-client:
    debug: false # change to true for mock Client use
    url: http://49.12.10.52:3383
    token: XXXXXXXXXXXXXXXXXXXXXXXXX
  kafka:
    bootstrap-address: kafka:9093
    notifications:
      start-debug: false
      topic-name: NOTIFICATION

freetonleague:
  service-user-prefix: SERVICE_
  system-user-prefix: SYSTEM_
  session:
    header-token-name: X-Auth-Token
    service-token-name: access_token #if change, than also change variable 'staticServiceTokenName'
  service:
    league-id:
      url: league-id:7700/api
      service-token: ifU#AxWveGwSAHevjJFx5S*d8K
    league-storage:
      url: league-storage:7702/api
      service-token: EqUEcXc3#iZCu5hQS!l33O6I3
    league-finance:
      service-token: QPhMMkF4GFEL5Vn6F45PHSaC1496
      balance-update-timeout-in-sec: 300
      product-billing-account-guid: 4cd64ee5-5f54-3eee-a9bb-f19164ef2ac2
      system-bonus-user-login: KdnIgwRY0qzedOZ6R2X6T9GtNDz # name of similar service-user from V025__fin_service_user_and_role.sql
      first-ton-bonus-name: first_ton_2021 # name bonus advertisement company (equals utm_source)
      auto-abort-transaction: false
      min-withdraw-value: 10
  docket:
    first_ton_docket_id: 4 #identifier of docket to automatically pay it's participant first ton to their account
    first_ton_bonus_amount: 1
  team:
    invitation:
      token-duration-in-sec: 432000
  tournament:
    auto-start: true

#LOGGING CONFIG
debug: false
debug-rest: true
stacktrace-rest: true

logging:
  level:
    root: INFO
    org:
      apache:
        kafka: INFO
        http:
          wire: INFO
      springframework: WARN #for detailed debug set DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      freetonleague: DEBUG
  file:
    name: \FreetonLeague\logs\League_Core_Tournament.log
# ===============================
#Configuring Feign
# ===============================
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        errorDecoder: com.freetonleague.core.cloudclient.util.FeignErrorDecoder
