# Use root/example as user/password credentials
version: '3.1'

services:
  postgres:
    container_name: "postgres_DB"
    build:
      context: ./docker
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
networks:
  postgres:
    driver: bridge

volumes:
  postgres: { }
